SELECT *
FROM BRIGHT_COFFEE_SHOP.COFFEE_SHOP.COFFEE_SHOP_TRANSACTIONS
limit 100;

~~ COUNT NR OF TRANSACTIONS 

SELECT COUNT(*) AS number_of_rows 
FROM BRIGHT_COFFEE_SHOP.COFFEE_SHOP.COFFEE_SHOP_TRANSACTIONS;

SELECT COUNT(TRANSACTION_ID) AS number_of_sales
FROM BRIGHT_COFFEE_SHOP.COFFEE_SHOP.COFFEE_SHOP_TRANSACTIONS;

~~ CALCULATE TOTAL NR OF UNITS SOLD AND REVENUE PER TRANSACTION

SELECT SUM(TRANSACTION_QTY) AS number_of_units_sold
FROM BRIGHT_COFFEE_SHOP.COFFEE_SHOP.COFFEE_SHOP_TRANSACTIONS;

SELECT TRANSACTION_QTY*UNIT_PRICE AS REVENUE_PER_TRANSACTION
FROM BRIGHT_COFFEE_SHOP.COFFEE_SHOP.COFFEE_SHOP_TRANSACTIONS;

~~ TOTAL REVENUE FOR THE 6 MONTHS

SELECT SUM(TRANSACTION_QTY*UNIT_PRICE) AS TOTAL_REVENUE,
            PRODUCT_CATEGORY
FROM BRIGHT_COFFEE_SHOP.COFFEE_SHOP.COFFEE_SHOP_TRANSACTIONS
GROUP BY PRODUCT_CATEGORY
ORDER BY TOTAL_REVENUE DESC;

~~ TOTAL REVENUE PER PRODUCT 

SELECT PRODUCT_CATEGORY,
       PRODUCT_TYPE,
        SUM(TRANSACTION_QTY*UNIT_PRICE) AS TOTAL_REVENUE
        FROM BRIGHT_COFFEE_SHOP.COFFEE_SHOP.COFFEE_SHOP_TRANSACTIONS
        GROUP BY PRODUCT_CATEGORY,
                 PRODUCT_TYPE
        ORDER BY TOTAL_REVENUE DESC
        LIMIT 3;

SELECT PRODUCT_CATEGORY,
        SUM(TRANSACTION_QTY*UNIT_PRICE) AS TOTAL_REVENUE
        FROM BRIGHT_COFFEE_SHOP.COFFEE_SHOP.COFFEE_SHOP_TRANSACTIONS
        GROUP BY PRODUCT_CATEGORY
        ORDER BY TOTAL_REVENUE ASC
        LIMIT 3;

~~ TOTAL REVENUE BY STORE LOCATION

SELECT STORE_LOCATION,
        SUM(TRANSACTION_QTY*UNIT_PRICE) AS TOTAL_REVENUE
        FROM BRIGHT_COFFEE_SHOP.COFFEE_SHOP.COFFEE_SHOP_TRANSACTIONS
        GROUP BY STORE_LOCATION
        ORDER BY TOTAL_REVENUE DESC
        LIMIT 3

~~ DATE FORMATTING

TO_CHAR(TO_DATE(TRANSACTION_DATE), 'YYYYMM') AS Month_id
DAYNAME(TO_DATE(TRANSACTION_DATE)) AS day_of_the_week;

~~ CALCULATE EARLIEST AND LATEST TIME

SELECT MIN(TRANSACTION_TIME)
FROM BRIGHT_COFFEE_SHOP.COFFEE_SHOP.COFFEE_SHOP_TRANSACTIONS;

SELECT MAX(TRANSACTION_TIME)
FROM BRIGHT_COFFEE_SHOP.COFFEE_SHOP.COFFEE_SHOP_TRANSACTIONS; 



~~ AGGREGATES
SELECT 
        SUM(TRANSACTION_QTY*UNIT_PRICE) AS total_revenue,
        SUM(TRANSACTION_QTY) AS number_of_units_sold,       
        COUNT(TRANSACTION_ID) AS number_of_sales,
        TO_CHAR(TRANSACTION_DATE, 'YYYYMM') AS month_id,
        MONTHNAME(TRANSACTION_DATE) AS MONTH_NAME,
        DAYNAME(TRANSACTION_DATE) AS DAY_NAME,
        PRODUCT_CATEGORY,
        PRODUCT_TYPE,
        STORE_LOCATION,
        PRODUCT_DETAIL,

~~ GROUPINGS

        CASE
            WHEN TRANSACTION_TIME BETWEEN '06:00:00' AND '11:59:59' THEN 'Morning'
            WHEN TRANSACTION_TIME BETWEEN '12:00:00' AND '15:59:59' THEN 'Afternoon'
            WHEN TRANSACTION_TIME BETWEEN '16:00:00' AND '20:59:59' THEN 'Evening'
            ELSE 'Night'
            END AS TIME_BUCKET, 
        CASE 
            WHEN SUM(TRANSACTION_QTY*UNIT_PRICE) BETWEEN 0 AND 20 THEN 'Low'
            WHEN SUM(TRANSACTION_QTY*UNIT_PRICE) BETWEEN 21 AND 40 THEN 'Medium'
            WHEN SUM(TRANSACTION_QTY*UNIT_PRICE) BETWEEN 41 AND 60 THEN 'High'
            ELSE 'Very high'
            END AS SPEND_BANDS,       
    FROM BRIGHT_COFFEE_SHOP.COFFEE_SHOP.COFFEE_SHOP_TRANSACTIONS
    GROUP BY TIME_BUCKET,
             PRODUCT_CATEGORY,
             PRODUCT_TYPE,
             STORE_LOCATION,
             PRODUCT_DETAIL,
             MONTH_ID,
             MONTH_NAME,
             DAY_NAME;
